#!/usr/bin/env bash
set -euo pipefail

# Determine repository root relative to this script
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_ENV_LOCAL="${REPO_ROOT}/.env.local"
FRONTEND_ENV_DIR="${REPO_ROOT}/frontend"
FRONTEND_ENV_LOCAL="${FRONTEND_ENV_DIR}/.env.local"

confirm_overwrite() {
  local file_path=$1
  if [[ -f "${file_path}" ]];
  then
    read -rp "${file_path} already exists. Overwrite? [y/N] " confirm
    if [[ ! "${confirm}" =~ ^[Yy]$ ]];
    then
      echo "Skipping ${file_path}"
      return 1
    fi
  fi
  return 0
}

read -rp "Enter the URL for your local backend (default: http://localhost:3001): " BACKEND_URL
BACKEND_URL="${BACKEND_URL:-http://localhost:3001}"

read -rp "Enter the URL for your local frontend (default: http://localhost:3000): " FRONTEND_URL
FRONTEND_URL="${FRONTEND_URL:-http://localhost:3000}"

overwrite_root=true
if ! confirm_overwrite "${ROOT_ENV_LOCAL}"; then
  overwrite_root=false
fi

if [[ "${overwrite_root}" == true ]]; then
  cat <<EOC > "${ROOT_ENV_LOCAL}"
# Generated by scripts/setup-dev-env.sh on $(date)
# Local overrides for the backend service
NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
FRONTEND_URL=${FRONTEND_URL}
BACKEND_URL=${BACKEND_URL}
EOC
  echo "Created ${ROOT_ENV_LOCAL}"
fi

mkdir -p "${FRONTEND_ENV_DIR}"
overwrite_frontend=true
if ! confirm_overwrite "${FRONTEND_ENV_LOCAL}"; then
  overwrite_frontend=false
fi

if [[ "${overwrite_frontend}" == true ]]; then
  cat <<EOC > "${FRONTEND_ENV_LOCAL}"
# Generated by scripts/setup-dev-env.sh on $(date)
NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
EOC
  echo "Created ${FRONTEND_ENV_LOCAL}"
fi

echo "Local development environment configuration complete."
